'use strict';
// Auto-generated from promti.db — DO NOT EDIT MANUALLY
// Sorted: complexity ASC, id ASC
const GAME_DATA = {
  phrases: [
    // complexity 0
    { id: 98,  phrase: "Мяч" },
    { id: 99,  phrase: "Чай" },
    // complexity 1
    { id: 87,  phrase: "Кот" },
    { id: 100, phrase: "Окно" },
    { id: 101, phrase: "Книга" },
    // complexity 2
    { id: 88,  phrase: "Дом" },
    { id: 102, phrase: "Стол" },
    { id: 103, phrase: "Лампа" },
    { id: 104, phrase: "Вода" },
    { id: 105, phrase: "Снег" },
    { id: 106, phrase: "Хлеб" },
    { id: 107, phrase: "Ключ" },
    { id: 108, phrase: "Река" },
    { id: 109, phrase: "Гора" },
    // complexity 3
    { id: 89,  phrase: "Зонт" },
    { id: 110, phrase: "Ветер" },
    { id: 111, phrase: "Пламя" },
    { id: 112, phrase: "Пыль" },
    { id: 113, phrase: "Сигнал" },
    { id: 114, phrase: "Шум" },
    { id: 115, phrase: "Тень" },
    { id: 116, phrase: "Погода" },
    { id: 117, phrase: "Глубина" },
    // complexity 4
    { id: 90,  phrase: "Туман" },
    { id: 118, phrase: "Скорость" },
    { id: 119, phrase: "Ошибка" },
    { id: 120, phrase: "Выбор" },
    { id: 121, phrase: "Цель" },
    { id: 122, phrase: "Идея" },
    { id: 123, phrase: "Мечта" },
    { id: 124, phrase: "Дружба" },
    { id: 125, phrase: "Знание" },
    { id: 126, phrase: "Привычка" },
    { id: 127, phrase: "Влияние" },
    // complexity 5
    { id: 91,  phrase: "Память" },
    { id: 128, phrase: "Алгоритм" },
    { id: 129, phrase: "Система" },
    { id: 130, phrase: "Модель" },
    { id: 131, phrase: "Данные" },
    { id: 132, phrase: "Контекст" },
    { id: 133, phrase: "Гипотеза" },
    // complexity 6
    { id: 92,  phrase: "Справедливость" },
    { id: 134, phrase: "Вероятность" },
    { id: 135, phrase: "Абстракция" },
    // complexity 7
    { id: 93,  phrase: "Интуиция" },
    { id: 136, phrase: "Осознание" },
    { id: 137, phrase: "Конфликт" },
    // complexity 8
    { id: 94,  phrase: "Парадокс" },
    { id: 138, phrase: "Эвристика" },
    // complexity 9
    { id: 95,  phrase: "Трансцендентность" },
    { id: 96,  phrase: "Энтропия" },
    { id: 97,  phrase: "Деконструкция" },
    { id: 139, phrase: "Сингулярность" },
    { id: 140, phrase: "Метамодерн" },
    // complexity 10
    { id: 46,  phrase: "Кремовый торт" },
    { id: 81,  phrase: "Красное яблоко" },
    { id: 82,  phrase: "Большой дом" },
    { id: 83,  phrase: "Синее небо" },
    { id: 84,  phrase: "Белый снег" },
    { id: 85,  phrase: "Горячий чай" },
    // complexity 20
    { id: 11,  phrase: "Кислый перец" },
    { id: 16,  phrase: "Сиплый свист" },
    { id: 17,  phrase: "Вязанный фартук" },
    { id: 19,  phrase: "Злая мышь" },
    { id: 22,  phrase: "Пюре из арбуза" },
    { id: 35,  phrase: "Семья енотов" },
    { id: 43,  phrase: "Мерзкий кот" },
    { id: 48,  phrase: "Свекла в сахаре" },
    { id: 51,  phrase: "Кошка в домике" },
    { id: 56,  phrase: "Берет с помпоном" },
    { id: 60,  phrase: "Сфера интересов" },
    { id: 61,  phrase: "Гречка на пару" },
    { id: 63,  phrase: "Журнал без обложки" },
    { id: 66,  phrase: "Луковый крем" },
    { id: 68,  phrase: "Шерстяные трусы" },
    { id: 77,  phrase: "Левый берег" },
    { id: 78,  phrase: "Соленый хлеб" },
    // complexity 30
    { id: 3,   phrase: "Мохнатый шмель" },
    { id: 9,   phrase: "Веер из купюр" },
    { id: 12,  phrase: "Вареный лось" },
    { id: 13,  phrase: "Розовый слон" },
    { id: 14,  phrase: "Горькая ваниль" },
    { id: 18,  phrase: "Пыльный валенок" },
    { id: 32,  phrase: "Сметана из майонеза" },
    { id: 36,  phrase: "Волшебная лестница" },
    { id: 38,  phrase: "Сухая акация" },
    { id: 44,  phrase: "Ручной штурвал" },
    { id: 49,  phrase: "Карате пацан" },
    { id: 52,  phrase: "Горький пряник" },
    { id: 55,  phrase: "Розовый фургон" },
    { id: 57,  phrase: "Чесночная пена" },
    { id: 58,  phrase: "Золотой скворечник" },
    { id: 70,  phrase: "Мокрый фундук" },
    { id: 73,  phrase: "Дорогой секатор" },
    { id: 74,  phrase: "Древний циклоп" },
    { id: 80,  phrase: "Эрозия бетона" },
    // complexity 40
    { id: 1,   phrase: "Шёлковая бочка" },
    { id: 4,   phrase: "Душистый хмель" },
    { id: 15,  phrase: "Надувной фен" },
    { id: 24,  phrase: "Шумный библиотекарь" },
    { id: 25,  phrase: "Фермерский браслет" },
    { id: 28,  phrase: "Деловой пингвин" },
    { id: 30,  phrase: "Пьяный самовар" },
    { id: 31,  phrase: "Свалка рубинов" },
    { id: 33,  phrase: "Учёный фазан" },
    { id: 37,  phrase: "Жаркий февраль" },
    { id: 39,  phrase: "Керамический смартфон" },
    { id: 53,  phrase: "Скорый троллейбус" },
    { id: 62,  phrase: "Магический скейтборд" },
    { id: 64,  phrase: "Блеск салфетки" },
    { id: 65,  phrase: "Флаг ларька" },
    { id: 67,  phrase: "Сердце пони" },
    { id: 69,  phrase: "Крепкий кипяток" },
    { id: 71,  phrase: "Добрый свояк" },
    { id: 75,  phrase: "Одинокий хутор" },
    { id: 76,  phrase: "Корабельный крен" },
    { id: 79,  phrase: "Плен любви" },
    // complexity 50
    { id: 2,   phrase: "Фотограф для фей" },
    { id: 6,   phrase: "Ночной кашпо" },
    { id: 21,  phrase: "Нефритовая клавиатура" },
    { id: 26,  phrase: "Вкусный фонарь" },
    { id: 29,  phrase: "Светский велосипед" },
    { id: 34,  phrase: "Фрак сантехника" },
    { id: 40,  phrase: "Фактический смысл" },
    { id: 42,  phrase: "Мучная феерия" },
    { id: 45,  phrase: "Пряный меч" },
    { id: 47,  phrase: "Картофельный тир" },
    { id: 59,  phrase: "Кварцевый отблеск" },
    { id: 72,  phrase: "Пряный лев" },
    // complexity 60
    { id: 5,   phrase: "Бриллиантовый инжектор" },
    { id: 8,   phrase: "Кофе из фанеры" },
    { id: 10,  phrase: "Фрегат в саду" },
    { id: 23,  phrase: "Ферзь из жвачки" },
    { id: 27,  phrase: "Пассивный фотон" },
    { id: 41,  phrase: "Кармический символ" },
    { id: 50,  phrase: "Поиск объекта" },
    { id: 54,  phrase: "Орнамент на дипломате" },
    // complexity 70
    { id: 20,  phrase: "Соловей разбойник" },
    // complexity 90
    { id: 7,   phrase: "Кузькина мать" },
    // complexity 100
    { id: 86,  phrase: "Сферический конь" }
  ],

  forbidden_words: [
    { id: 1,   phrase_id: 1,   root: "боч" },
    { id: 2,   phrase_id: 1,   root: "шёлк" },
    { id: 3,   phrase_id: 1,   root: "шелк" },
    { id: 4,   phrase_id: 2,   root: "фото" },
    { id: 5,   phrase_id: 2,   root: "фея" },
    { id: 6,   phrase_id: 2,   root: "фей" },
    { id: 7,   phrase_id: 3,   root: "мох" },
    { id: 10,  phrase_id: 3,   root: "шмел" },
    { id: 8,   phrase_id: 4,   root: "душ" },
    { id: 9,   phrase_id: 4,   root: "дух" },
    { id: 11,  phrase_id: 4,   root: "хмел" },
    { id: 12,  phrase_id: 5,   root: "брлил" },
    { id: 13,  phrase_id: 5,   root: "инжек" },
    { id: 14,  phrase_id: 6,   root: "ноч" },
    { id: 15,  phrase_id: 6,   root: "каш" },
    { id: 16,  phrase_id: 7,   root: "кузь" },
    { id: 17,  phrase_id: 7,   root: "мат" },
    { id: 18,  phrase_id: 7,   root: "мам" },
    { id: 19,  phrase_id: 8,   root: "коф" },
    { id: 20,  phrase_id: 8,   root: "фан" },
    { id: 21,  phrase_id: 9,   root: "веер" },
    { id: 22,  phrase_id: 9,   root: "купюр" },
    { id: 23,  phrase_id: 10,  root: "фрегат" },
    { id: 24,  phrase_id: 10,  root: "сад" },
    { id: 25,  phrase_id: 11,  root: "кисл" },
    { id: 26,  phrase_id: 11,  root: "пер" },
    { id: 27,  phrase_id: 12,  root: "вар" },
    { id: 28,  phrase_id: 12,  root: "лос" },
    { id: 29,  phrase_id: 13,  root: "роз" },
    { id: 30,  phrase_id: 13,  root: "слон" },
    { id: 31,  phrase_id: 14,  root: "гор" },
    { id: 32,  phrase_id: 14,  root: "ванил" },
    { id: 33,  phrase_id: 15,  root: "дут" },
    { id: 34,  phrase_id: 15,  root: "дув" },
    { id: 35,  phrase_id: 15,  root: "фен" },
    { id: 36,  phrase_id: 16,  root: "свист" },
    { id: 37,  phrase_id: 16,  root: "сип" },
    { id: 38,  phrase_id: 17,  root: "вяз" },
    { id: 39,  phrase_id: 17,  root: "фарт" },
    { id: 42,  phrase_id: 18,  root: "пыл" },
    { id: 43,  phrase_id: 18,  root: "пыль" },
    { id: 44,  phrase_id: 18,  root: "вал" },
    { id: 45,  phrase_id: 19,  root: "био" },
    { id: 46,  phrase_id: 19,  root: "грыз" },
    { id: 47,  phrase_id: 19,  root: "зоо" },
    { id: 48,  phrase_id: 19,  root: "клик" },
    { id: 49,  phrase_id: 19,  root: "компьютер" },
    { id: 50,  phrase_id: 19,  root: "манипул" },
    { id: 51,  phrase_id: 19,  root: "мыш" },
    { id: 52,  phrase_id: 19,  root: "мышь" },
    { id: 53,  phrase_id: 19,  root: "числ" },
    { id: 54,  phrase_id: 19,  root: "зла" },
    { id: 55,  phrase_id: 19,  root: "зло" },
    { id: 56,  phrase_id: 20,  root: "солов" },
    { id: 57,  phrase_id: 20,  root: "разб" },
    { id: 58,  phrase_id: 21,  root: "нефр" },
    { id: 59,  phrase_id: 21,  root: "клав" },
    { id: 60,  phrase_id: 22,  root: "пюр" },
    { id: 61,  phrase_id: 22,  root: "арб" },
    { id: 62,  phrase_id: 23,  root: "фер" },
    { id: 63,  phrase_id: 23,  root: "жва" },
    { id: 65,  phrase_id: 24,  root: "библи" },
    { id: 70,  phrase_id: 24,  root: "книг" },
    { id: 76,  phrase_id: 24,  root: "работ" },
    { id: 77,  phrase_id: 24,  root: "тек" },
    { id: 78,  phrase_id: 24,  root: "теч" },
    { id: 81,  phrase_id: 25,  root: "браслет" },
    { id: 82,  phrase_id: 25,  root: "фермер" },
    { id: 83,  phrase_id: 26,  root: "вкус" },
    { id: 84,  phrase_id: 26,  root: "фонар" },
    { id: 85,  phrase_id: 27,  root: "фот" },
    { id: 86,  phrase_id: 27,  root: "эшафот" },
    { id: 87,  phrase_id: 27,  root: "пасс" },
    { id: 88,  phrase_id: 28,  root: "богадел" },
    { id: 89,  phrase_id: 28,  root: "вождел" },
    { id: 90,  phrase_id: 28,  root: "дел" },
    { id: 91,  phrase_id: 28,  root: "крендел" },
    { id: 92,  phrase_id: 28,  root: "кудел" },
    { id: 93,  phrase_id: 28,  root: "мендел" },
    { id: 94,  phrase_id: 28,  root: "модел" },
    { id: 95,  phrase_id: 28,  root: "недел" },
    { id: 96,  phrase_id: 28,  root: "определ" },
    { id: 97,  phrase_id: 28,  root: "пингвин" },
    { id: 98,  phrase_id: 28,  root: "предел" },
    { id: 99,  phrase_id: 28,  root: "продел" },
    { id: 100, phrase_id: 28,  root: "пудел" },
    { id: 101, phrase_id: 28,  root: "седёл" },
    { id: 102, phrase_id: 28,  root: "удел" },
    { id: 103, phrase_id: 29,  root: "велосипед" },
    { id: 104, phrase_id: 29,  root: "просвет" },
    { id: 105, phrase_id: 29,  root: "свет" },
    { id: 106, phrase_id: 30,  root: "ассам" },
    { id: 107, phrase_id: 30,  root: "выпь" },
    { id: 108, phrase_id: 30,  root: "кипь" },
    { id: 109, phrase_id: 30,  root: "копь" },
    { id: 110, phrase_id: 30,  root: "крепь" },
    { id: 111, phrase_id: 30,  root: "оторопь" },
    { id: 112, phrase_id: 30,  root: "пь" },
    { id: 113, phrase_id: 30,  root: "сам" },
    { id: 114, phrase_id: 30,  root: "степь" },
    { id: 115, phrase_id: 30,  root: "ступь" },
    { id: 116, phrase_id: 30,  root: "сыпь" },
    { id: 117, phrase_id: 30,  root: "топь" },
    { id: 118, phrase_id: 30,  root: "трепь" },
    { id: 119, phrase_id: 30,  root: "тряпь" },
    { id: 120, phrase_id: 30,  root: "хлопь" },
    { id: 121, phrase_id: 30,  root: "хлупь" },
    { id: 122, phrase_id: 30,  root: "цепь" },
    { id: 123, phrase_id: 30,  root: "щупь" },
    { id: 124, phrase_id: 31,  root: "бахвал" },
    { id: 125, phrase_id: 31,  root: "вал" },
    { id: 126, phrase_id: 31,  root: "интервал" },
    { id: 127, phrase_id: 31,  root: "карнавал" },
    { id: 128, phrase_id: 31,  root: "квал" },
    { id: 129, phrase_id: 31,  root: "овал" },
    { id: 130, phrase_id: 31,  root: "подвал" },
    { id: 131, phrase_id: 31,  root: "превал" },
    { id: 132, phrase_id: 31,  root: "хвал" },
    { id: 133, phrase_id: 31,  root: "шквал" },
    { id: 134, phrase_id: 31,  root: "штурвал" },
    { id: 135, phrase_id: 32,  root: "смет" },
    { id: 136, phrase_id: 32,  root: "май" },
    { id: 137, phrase_id: 33,  root: "фазан" },
    { id: 138, phrase_id: 33,  root: "учен" },
    { id: 139, phrase_id: 33,  root: "учён" },
    { id: 140, phrase_id: 34,  root: "лавсан" },
    { id: 141, phrase_id: 34,  root: "нганасан" },
    { id: 142, phrase_id: 34,  root: "осан" },
    { id: 143, phrase_id: 34,  root: "сан" },
    { id: 144, phrase_id: 34,  root: "фрак" },
    { id: 145, phrase_id: 35,  root: "восемь" },
    { id: 146, phrase_id: 35,  root: "семь" },
    { id: 147, phrase_id: 35,  root: "ено" },
    { id: 148, phrase_id: 36,  root: "блест" },
    { id: 149, phrase_id: 36,  root: "блёст" },
    { id: 150, phrase_id: 36,  root: "доблест" },
    { id: 151, phrase_id: 36,  root: "клест" },
    { id: 152, phrase_id: 36,  root: "клёст" },
    { id: 153, phrase_id: 36,  root: "лест" },
    { id: 154, phrase_id: 36,  root: "прелест" },
    { id: 155, phrase_id: 36,  root: "хлест" },
    { id: 156, phrase_id: 36,  root: "хлёст" },
    { id: 157, phrase_id: 36,  root: "шелест" },
    { id: 158, phrase_id: 36,  root: "волш" },
    { id: 159, phrase_id: 37,  root: "аджар" },
    { id: 160, phrase_id: 37,  root: "жар" },
    { id: 161, phrase_id: 37,  root: "мажар" },
    { id: 162, phrase_id: 37,  root: "поджар" },
    { id: 163, phrase_id: 37,  root: "пожар" },
    { id: 164, phrase_id: 37,  root: "февраль" },
    { id: 165, phrase_id: 38,  root: "акаци" },
    { id: 166, phrase_id: 38,  root: "вакаци" },
    { id: 167, phrase_id: 38,  root: "сух" },
    { id: 168, phrase_id: 39,  root: "керам" },
    { id: 169, phrase_id: 39,  root: "смар" },
    { id: 170, phrase_id: 40,  root: "артефакт" },
    { id: 171, phrase_id: 40,  root: "замысл" },
    { id: 172, phrase_id: 40,  root: "коромысл" },
    { id: 173, phrase_id: 40,  root: "мысл" },
    { id: 174, phrase_id: 40,  root: "промысл" },
    { id: 175, phrase_id: 40,  root: "факт" },
    { id: 176, phrase_id: 41,  root: "символ" },
    { id: 177, phrase_id: 41,  root: "карм" },
    { id: 178, phrase_id: 42,  root: "феери" },
    { id: 179, phrase_id: 42,  root: "муч" },
    { id: 180, phrase_id: 42,  root: "мук" },
    { id: 181, phrase_id: 43,  root: "мерз" },
    { id: 182, phrase_id: 43,  root: "кот" },
    { id: 183, phrase_id: 44,  root: "вруч" },
    { id: 184, phrase_id: 44,  root: "выруч" },
    { id: 185, phrase_id: 44,  root: "заруч" },
    { id: 186, phrase_id: 44,  root: "круч" },
    { id: 187, phrase_id: 44,  root: "обруч" },
    { id: 188, phrase_id: 44,  root: "поруч" },
    { id: 189, phrase_id: 44,  root: "руч" },
    { id: 190, phrase_id: 44,  root: "удруч" },
    { id: 191, phrase_id: 44,  root: "штурвал" },
    { id: 192, phrase_id: 45,  root: "замеч" },
    { id: 193, phrase_id: 45,  root: "меч" },
    { id: 194, phrase_id: 45,  root: "предмеч" },
    { id: 195, phrase_id: 45,  root: "примеч" },
    { id: 196, phrase_id: 45,  root: "прян" },
    { id: 197, phrase_id: 46,  root: "крем" },
    { id: 198, phrase_id: 46,  root: "реторт" },
    { id: 199, phrase_id: 46,  root: "торт" },
    { id: 200, phrase_id: 47,  root: "дезертир" },
    { id: 201, phrase_id: 47,  root: "истир" },
    { id: 202, phrase_id: 47,  root: "картофель" },
    { id: 203, phrase_id: 47,  root: "квартир" },
    { id: 204, phrase_id: 47,  root: "клистир" },
    { id: 205, phrase_id: 47,  root: "мортир" },
    { id: 206, phrase_id: 47,  root: "простир" },
    { id: 207, phrase_id: 47,  root: "пунктир" },
    { id: 208, phrase_id: 47,  root: "ретир" },
    { id: 209, phrase_id: 47,  root: "сатир" },
    { id: 210, phrase_id: 47,  root: "сортир" },
    { id: 211, phrase_id: 47,  root: "стир" },
    { id: 212, phrase_id: 47,  root: "тир" },
    { id: 213, phrase_id: 47,  root: "трактир" },
    { id: 214, phrase_id: 47,  root: "транспортир" },
    { id: 215, phrase_id: 48,  root: "свек" },
    { id: 216, phrase_id: 48,  root: "сах" },
    { id: 217, phrase_id: 49,  root: "пацан" },
    { id: 218, phrase_id: 49,  root: "кар" },
    { id: 219, phrase_id: 50,  root: "василиск" },
    { id: 220, phrase_id: 50,  root: "диск" },
    { id: 221, phrase_id: 50,  root: "заиск" },
    { id: 222, phrase_id: 50,  root: "иск" },
    { id: 223, phrase_id: 50,  root: "конфиск" },
    { id: 224, phrase_id: 50,  root: "мениск" },
    { id: 225, phrase_id: 50,  root: "миск" },
    { id: 226, phrase_id: 50,  root: "обелиск" },
    { id: 227, phrase_id: 50,  root: "писк" },
    { id: 228, phrase_id: 50,  root: "риск" },
    { id: 229, phrase_id: 50,  root: "сниск" },
    { id: 230, phrase_id: 50,  root: "сосиск" },
    { id: 231, phrase_id: 50,  root: "тамариск" },
    { id: 232, phrase_id: 50,  root: "тиск" },
    { id: 233, phrase_id: 50,  root: "фиск" },
    { id: 234, phrase_id: 50,  root: "франциск" },
    { id: 235, phrase_id: 50,  root: "объ" },
    { id: 236, phrase_id: 51,  root: "кош" },
    { id: 237, phrase_id: 51,  root: "дом" },
    { id: 238, phrase_id: 52,  root: "горьк" },
    { id: 239, phrase_id: 52,  root: "пряник" },
    { id: 240, phrase_id: 53,  root: "искор" },
    { id: 241, phrase_id: 53,  root: "скор" },
    { id: 242, phrase_id: 53,  root: "троллей" },
    { id: 243, phrase_id: 54,  root: "орн" },
    { id: 244, phrase_id: 54,  root: "дип" },
    { id: 245, phrase_id: 55,  root: "розов" },
    { id: 246, phrase_id: 55,  root: "фургон" },
    { id: 247, phrase_id: 56,  root: "бер" },
    { id: 248, phrase_id: 56,  root: "пом" },
    { id: 249, phrase_id: 57,  root: "ерепен" },
    { id: 250, phrase_id: 57,  root: "копён" },
    { id: 251, phrase_id: 57,  root: "пен" },
    { id: 252, phrase_id: 57,  root: "постепен" },
    { id: 253, phrase_id: 57,  root: "пён" },
    { id: 254, phrase_id: 57,  root: "степен" },
    { id: 255, phrase_id: 57,  root: "терпен" },
    { id: 256, phrase_id: 57,  root: "успен" },
    { id: 257, phrase_id: 57,  root: "цепен" },
    { id: 258, phrase_id: 57,  root: "чесн" },
    { id: 259, phrase_id: 58,  root: "золот" },
    { id: 260, phrase_id: 58,  root: "сквореч" },
    { id: 261, phrase_id: 59,  root: "блеск" },
    { id: 262, phrase_id: 59,  root: "блёск" },
    { id: 263, phrase_id: 59,  root: "кварц" },
    { id: 264, phrase_id: 60,  root: "атмосфер" },
    { id: 265, phrase_id: 60,  root: "сфер" },
    { id: 266, phrase_id: 60,  root: "инт" },
    { id: 267, phrase_id: 61,  root: "греч" },
    { id: 268, phrase_id: 61,  root: "пар" },
    { id: 269, phrase_id: 62,  root: "колымаг" },
    { id: 270, phrase_id: 62,  root: "маг" },
    { id: 271, phrase_id: 62,  root: "скейт" },
    { id: 272, phrase_id: 63,  root: "жур" },
    { id: 273, phrase_id: 63,  root: "обл" },
    { id: 274, phrase_id: 64,  root: "блеск" },
    { id: 275, phrase_id: 64,  root: "блёск" },
    { id: 276, phrase_id: 64,  root: "салф" },
    { id: 277, phrase_id: 65,  root: "флаг" },
    { id: 278, phrase_id: 65,  root: "лар" },
    { id: 279, phrase_id: 66,  root: "архалук" },
    { id: 280, phrase_id: 66,  root: "каблук" },
    { id: 281, phrase_id: 66,  root: "крем" },
    { id: 282, phrase_id: 66,  root: "лук" },
    { id: 283, phrase_id: 66,  root: "тузлук" },
    { id: 284, phrase_id: 67,  root: "сердц" },
    { id: 285, phrase_id: 67,  root: "пон" },
    { id: 286, phrase_id: 68,  root: "трус" },
    { id: 287, phrase_id: 68,  root: "цитрус" },
    { id: 288, phrase_id: 68,  root: "этрус" },
    { id: 289, phrase_id: 68,  root: "шерст" },
    { id: 290, phrase_id: 69,  root: "кип" },
    { id: 291, phrase_id: 69,  root: "крепк" },
    { id: 292, phrase_id: 69,  root: "экип" },
    { id: 293, phrase_id: 70,  root: "мокр" },
    { id: 294, phrase_id: 70,  root: "фундук" },
    { id: 295, phrase_id: 71,  root: "добр" },
    { id: 296, phrase_id: 71,  root: "одобр" },
    { id: 297, phrase_id: 71,  root: "свояк" },
    { id: 298, phrase_id: 71,  root: "сдобр" },
    { id: 299, phrase_id: 71,  root: "удобр" },
    { id: 300, phrase_id: 72,  root: "прян" },
    { id: 301, phrase_id: 72,  root: "лев" },
    { id: 302, phrase_id: 73,  root: "дорог" },
    { id: 303, phrase_id: 73,  root: "отсек" },
    { id: 304, phrase_id: 73,  root: "пасек" },
    { id: 305, phrase_id: 73,  root: "сек" },
    { id: 306, phrase_id: 73,  root: "судорог" },
    { id: 307, phrase_id: 73,  root: "сусек" },
    { id: 308, phrase_id: 74,  root: "древн" },
    { id: 309, phrase_id: 74,  root: "циклоп" },
    { id: 310, phrase_id: 75,  root: "гетеродин" },
    { id: 311, phrase_id: 75,  root: "господин" },
    { id: 312, phrase_id: 75,  root: "один" },
    { id: 313, phrase_id: 75,  root: "смородин" },
    { id: 314, phrase_id: 75,  root: "хутор" },
    { id: 315, phrase_id: 76,  root: "корабель" },
    { id: 316, phrase_id: 76,  root: "крен" },
    { id: 317, phrase_id: 77,  root: "берег" },
    { id: 318, phrase_id: 77,  root: "берёг" },
    { id: 319, phrase_id: 77,  root: "блев" },
    { id: 320, phrase_id: 77,  root: "калёв" },
    { id: 321, phrase_id: 77,  root: "клев" },
    { id: 322, phrase_id: 77,  root: "клёв" },
    { id: 323, phrase_id: 77,  root: "лев" },
    { id: 324, phrase_id: 77,  root: "малёв" },
    { id: 325, phrase_id: 77,  root: "палев" },
    { id: 326, phrase_id: 77,  root: "пеклёв" },
    { id: 327, phrase_id: 77,  root: "плев" },
    { id: 328, phrase_id: 77,  root: "плёв" },
    { id: 329, phrase_id: 77,  root: "хлев" },
    { id: 330, phrase_id: 77,  root: "шпаклёв" },
    { id: 331, phrase_id: 78,  root: "антресол" },
    { id: 332, phrase_id: 78,  root: "мосол" },
    { id: 333, phrase_id: 78,  root: "мусол" },
    { id: 334, phrase_id: 78,  root: "оксол" },
    { id: 335, phrase_id: 78,  root: "прасол" },
    { id: 336, phrase_id: 78,  root: "сол" },
    { id: 337, phrase_id: 78,  root: "сусол" },
    { id: 338, phrase_id: 78,  root: "фасол" },
    { id: 339, phrase_id: 78,  root: "фиксол" },
    { id: 340, phrase_id: 78,  root: "хлеб" },
    { id: 341, phrase_id: 78,  root: "хлёб" },
    { id: 342, phrase_id: 79,  root: "кримплен" },
    { id: 343, phrase_id: 79,  root: "плен" },
    { id: 344, phrase_id: 79,  root: "люб" },
    { id: 345, phrase_id: 80,  root: "эрози" },
    { id: 346, phrase_id: 80,  root: "бет" },
    { id: 347, phrase_id: 81,  root: "яблок" },
    { id: 348, phrase_id: 81,  root: "крас" },
    { id: 349, phrase_id: 82,  root: "больш" },
    { id: 350, phrase_id: 82,  root: "дом" },
    { id: 351, phrase_id: 82,  root: "мажордом" },
    { id: 352, phrase_id: 82,  root: "осведом" },
    { id: 353, phrase_id: 82,  root: "скопидом" },
    { id: 354, phrase_id: 82,  root: "содом" },
    { id: 355, phrase_id: 82,  root: "уведом" },
    { id: 356, phrase_id: 83,  root: "неб" },
    { id: 357, phrase_id: 83,  root: "нёб" },
    { id: 358, phrase_id: 83,  root: "син" },
    { id: 359, phrase_id: 84,  root: "бел" },
    { id: 360, phrase_id: 84,  root: "дебел" },
    { id: 361, phrase_id: 84,  root: "кобел" },
    { id: 362, phrase_id: 84,  root: "корабел" },
    { id: 363, phrase_id: 84,  root: "мебел" },
    { id: 364, phrase_id: 84,  root: "мирабел" },
    { id: 365, phrase_id: 84,  root: "снег" },
    { id: 366, phrase_id: 84,  root: "стебел" },
    { id: 367, phrase_id: 84,  root: "штабел" },
    { id: 368, phrase_id: 85,  root: "горяч" },
    { id: 369, phrase_id: 85,  root: "чай" },
    { id: 370, phrase_id: 86,  root: "сфер" },
    { id: 371, phrase_id: 86,  root: "конь" },
    { id: 372, phrase_id: 87,  root: "кот" },
    { id: 373, phrase_id: 88,  root: "дом" },
    { id: 374, phrase_id: 88,  root: "мажордом" },
    { id: 375, phrase_id: 88,  root: "осведом" },
    { id: 376, phrase_id: 88,  root: "скопидом" },
    { id: 377, phrase_id: 88,  root: "содом" },
    { id: 378, phrase_id: 88,  root: "уведом" },
    { id: 379, phrase_id: 89,  root: "горизонт" },
    { id: 380, phrase_id: 89,  root: "зонт" },
    { id: 381, phrase_id: 90,  root: "тум" },
    { id: 382, phrase_id: 91,  root: "память" },
    { id: 383, phrase_id: 92,  root: "справедлив" },
    { id: 384, phrase_id: 93,  root: "интуиц" },
    { id: 385, phrase_id: 94,  root: "парадокс" },
    { id: 386, phrase_id: 95,  root: "тран" },
    { id: 387, phrase_id: 95,  root: "ценд" },
    { id: 388, phrase_id: 96,  root: "гармон" },
    { id: 389, phrase_id: 96,  root: "оуэн" },
    { id: 390, phrase_id: 96,  root: "эн" },
    { id: 391, phrase_id: 97,  root: "деконструкц" },
    { id: 392, phrase_id: 98,  root: "мяч" },
    { id: 393, phrase_id: 98,  root: "мячик" },
    { id: 394, phrase_id: 99,  root: "чай" },
    { id: 395, phrase_id: 99,  root: "чаёк" },
    { id: 396, phrase_id: 99,  root: "чаек" },
    { id: 397, phrase_id: 100, root: "окн" },
    { id: 398, phrase_id: 101, root: "книг" },
    { id: 399, phrase_id: 102, root: "стол" },
    { id: 400, phrase_id: 102, root: "столик" },
    { id: 401, phrase_id: 103, root: "ламп" },
    { id: 402, phrase_id: 104, root: "вод" },
    { id: 403, phrase_id: 105, root: "снег" },
    { id: 404, phrase_id: 105, root: "снеж" },
    { id: 405, phrase_id: 106, root: "хлеб" },
    { id: 406, phrase_id: 107, root: "ключ" },
    { id: 407, phrase_id: 108, root: "рек" },
    { id: 408, phrase_id: 109, root: "гор" },
    { id: 409, phrase_id: 110, root: "ветер" },
    { id: 410, phrase_id: 110, root: "ветр" },
    { id: 411, phrase_id: 111, root: "плам" },
    { id: 412, phrase_id: 112, root: "пыл" },
    { id: 413, phrase_id: 113, root: "сигнал" },
    { id: 414, phrase_id: 113, root: "сигн" },
    { id: 415, phrase_id: 114, root: "шум" },
    { id: 416, phrase_id: 115, root: "тен" },
    { id: 417, phrase_id: 115, root: "тень" },
    { id: 418, phrase_id: 116, root: "погод" },
    { id: 419, phrase_id: 117, root: "глубин" },
    { id: 420, phrase_id: 118, root: "скор" },
    { id: 421, phrase_id: 118, root: "скорост" },
    { id: 422, phrase_id: 119, root: "ошиб" },
    { id: 423, phrase_id: 120, root: "выбор" },
    { id: 424, phrase_id: 121, root: "цел" },
    { id: 425, phrase_id: 122, root: "иде" },
    { id: 426, phrase_id: 123, root: "мечт" },
    { id: 427, phrase_id: 124, root: "друж" },
    { id: 428, phrase_id: 125, root: "знан" },
    { id: 429, phrase_id: 126, root: "привыч" },
    { id: 430, phrase_id: 127, root: "влия" },
    { id: 431, phrase_id: 128, root: "алгоритм" },
    { id: 432, phrase_id: 128, root: "алгор" },
    { id: 433, phrase_id: 129, root: "систем" },
    { id: 434, phrase_id: 130, root: "модел" },
    { id: 435, phrase_id: 131, root: "данн" },
    { id: 436, phrase_id: 131, root: "дан" },
    { id: 437, phrase_id: 132, root: "контекст" },
    { id: 438, phrase_id: 132, root: "контексту" },
    { id: 439, phrase_id: 133, root: "гипотез" },
    { id: 440, phrase_id: 133, root: "гипот" },
    { id: 441, phrase_id: 134, root: "вероят" },
    { id: 442, phrase_id: 134, root: "вероятн" },
    { id: 443, phrase_id: 135, root: "абстракц" },
    { id: 444, phrase_id: 135, root: "абстракт" },
    { id: 445, phrase_id: 136, root: "осозна" },
    { id: 446, phrase_id: 137, root: "конфликт" },
    { id: 447, phrase_id: 138, root: "эврист" },
    { id: 448, phrase_id: 138, root: "эвр" },
    { id: 449, phrase_id: 139, root: "сингул" },
    { id: 450, phrase_id: 139, root: "сингуляр" },
    { id: 451, phrase_id: 139, root: "сингу" },
    { id: 452, phrase_id: 140, root: "метамодерн" }
  ]
};
